# Generated by Django 3.0.6 on 2020-05-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='default_county',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='default_dob',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='default_phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='default_postcode',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='default_street_address1',
            new_name='street_address1',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='default_street_address2',
            new_name='street_address2',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='default_town_or_city',
            new_name='town_or_city',
        ),
    ]
