# Generated by Django 3.0.6 on 2020-05-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200514_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
