# Generated by Django 3.0.6 on 2020-05-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_user_profile_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile',
            options={'verbose_name_plural': 'User Profile'},
        ),
    ]
