# Generated by Django 3.0.6 on 2020-05-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200515_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='county',
            field=models.CharField(default='default county', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='dob',
            field=models.DateField(default='2010-03-03', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='full_name',
            field=models.CharField(default='default full_name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone_number',
            field=models.CharField(default='default phone_number', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='postcode',
            field=models.CharField(default='default postcode', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='street_address1',
            field=models.CharField(default='street_address1', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='street_address2',
            field=models.CharField(default='default streetaddress2', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='town_or_city',
            field=models.CharField(default='default town_or_city', max_length=40),
            preserve_default=False,
        ),
    ]
