# Generated by Django 3.0.6 on 2020-05-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200508_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='modifed',
            new_name='updated',
        ),
    ]
