# Generated by Django 3.0.6 on 2020-05-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200506_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
